### PR TITLE
[FIX] [account_operating_unit] iterated recordset

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
@aheficent @lreficent @mreficent fixed iteration minor issue.

cc @jbeficent

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Thank you @darshan-serpent

**Review by LoisRForgeFlow — APPROVED** [review]
It seems ok for me too.

**Comment by LoisRForgeFlow** [comment]
Maybe we should create a branch for this fix since this is actually merged in OCA. So, @darshan-serpent can you make a PR directly to the OCA with this fix please?

We will approve it there.

**Comment by serpentcs-dev1** [comment]
Yes right, @lreficent but I am not sure how can I send a PR to OCA/operating-unit as I have forked it from Eficent

**Comment by serpentcs-dev1** [comment]
Better if you guys can make this minor change and then make a PR to OCA.

**Comment by LoisRForgeFlow** [comment]
ok, doing it

**Pull request closed without merging**
